---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    tests:
      test1:
        name: A
        age: 12
        gender: M

      test2:
        name: K
        age: 10
        gender: F

  tasks:
    - debug: msg="{{ item['key'] }} name={{ item['value']['name'] }} age={{ item['value']['age'] }} gender={{ item['value']['gender'] }}"
      with_dict: "{{ tests }}"
